spring:
  redis:
    host: 47.103.155.255
    password: 123456
    port: 6379
    jedis:
      pool:
        min-idle: 0
        max-idle: 8
        max-active: 80
        max-wait: 30000
        timeout: 3000